export const languagePresets: Record<string, Record<string, string>> = {
  pt: {
    'auth.welcome_back': 'Bem-vindo de volta!',
    'auth.subtitle': 'Acesse sua área exclusiva',
    'auth.login': 'Entrar',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.restricted_access': 'Aviso de Acesso Restrito',
    'auth.restricted_access_msg': 'Acesso restrito a alunas cadastradas.',
    'auth.logout_success': 'Até logo!',
    'auth.support_box': 'Precisa de Suporte?',
    'auth.support_description': 'Nossa equipe está pronta para te ajudar com qualquer dúvida ou problema técnico.',
    'auth.whatsapp_label': 'WhatsApp',
    'auth.email_label': 'E-mail',
    'auth.user_not_found': 'Usuário não encontrado',
    'auth.disclaimer': 'Ao entrar, você concorda com nossos Termos de Uso e Política de Privacidade. Maternidade Premium! © 2026',
    'nav.home': 'Início',
    'nav.community': 'Comunidade',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'global.save': 'Salvar',
    'global.cancel': 'Cancelar',
    'global.delete': 'Excluir',
    'global.back': 'Voltar',
    'global.logout': 'Sair',
    'dashboard.courses_paid': 'Meus Cursos',
    'dashboard.courses_free': 'Produtos Principais',
    'dashboard.courses_bonus': 'Meus Bônus',
    'course.progress': 'Seu Progresso',
    'course.your_progress': 'Seu Progresso',
    'course.lessons': 'Aulas',
    'course.content': 'Conteúdo',
    'course.no_media': 'Aula sem conteúdo de mídia',
    'course.lesson_completed': 'Aula concluída!',
    'course.prev_lesson': 'Aula Anterior',
    'course.next_lesson': 'Próxima Aula',
    'course.materials': 'Materiais',
    'course.lesson_unmarked': 'Aula marcada como não concluída',
    'course.lesson_completed_btn': 'AULA CONCLUÍDA',
    'course.complete_lesson_btn': 'CONCLUIR AULA',
    'course.end_label': 'Fim',
    'course.support_description': 'Nossa equipe está pronta para te ajudar.',
    'course.premium_content': 'CONTEÚDO PREMIUM',
    'course.unlock_button': 'LIBERAR ACESSO AGORA',
    'course.secure_payment': 'Pagamento 100% Seguro • Acesso Imediato',
    'course.schedule_title': 'Cronograma do Curso',
    'course.completed': 'CONCLUÍDO',
    'course.continue': 'CONTINUAR',
    'course.start': 'COMEÇAR',
    'community.title': 'Comunidade',
    'community.subtitle': 'Compartilhe sua jornada com outras mães',
    'community.input_placeholder': 'O que você quer compartilhar?',
    'community.post': 'Publicar',
    'community.like': 'Curtir',
    'community.reply': 'Responder',
    'community.delete_post': 'Excluir Post',
    'community.add_photo': 'Adicionar foto',
    'community.post_sent': 'Post enviado!',
    'community.post_updated': 'Post atualizado!',
    'community.edit_post': 'Editar Publicação',
    'community.delete_post_confirm': 'Excluir Publicação?',
    'community.delete_comment_confirm': 'Excluir Comentário?',
    'community.comment_placeholder': 'Escreva um comentário...',
    'community.delete_post_desc': 'Esta ação não pode ser desfeita. A publicação e sua imagem serão removidas permanentemente.',
    'community.delete_comment_desc': 'O comentário será removido permanentemente.',
    'community.delete_success': 'Publicação excluída com sucesso!',
    'community.delete_error': 'Erro ao excluir publicação',
    'community.comment_delete_success': 'Comentário excluído com sucesso!',
    'community.comment_delete_error': 'Erro ao excluir comentário',
    'community.date_format': "d 'de' MMM, HH:mm",
    'community.locale': 'ptBR',
    'profile.title': 'Meu Perfil',
    'profile.subtitle': 'Gerencie suas informações',
    'profile.save_changes': 'Salvar Alterações',
    'profile.change_password': 'Alterar Senha',
    'profile.update_success': 'Perfil atualizado com sucesso!',
    'profile.avatar_success': 'Foto de perfil atualizada!',
    'profile.password_mismatch': 'As senhas não coincidem',
    'profile.password_success': 'Senha atualizada com sucesso!',
    'profile.change_photo': 'Trocar foto',
    'profile.info_title': 'Informações do Usuário',
    'profile.access': 'Acesso',
    'profile.email_restricted': 'O e-mail não pode ser alterado.',
    'profile.name_label': 'Nome',
    'profile.name_placeholder': 'Seu nome',
    'profile.phone_label': 'Telefone (WhatsApp)',
    'profile.phone_country_code': 'Código do país',
    'profile.phone_number_label': 'Telefone com código de área',
    'profile.security_title': 'Segurança',
    'profile.new_password_label': 'Nova Senha',
    'profile.confirm_password_label': 'Confirmar Nova Senha',
    'profile.update_password': 'ATUALIZAR SENHA',
    'profile.push_title': 'Notificações Push',
    'profile.push_description': 'Receba avisos importantes, novas aulas e atualizações da comunidade diretamente no seu navegador.',
    'profile.status_support': 'Suporte',
    'profile.status_available': 'DISPONÍVEL',
    'profile.status_not_supported': 'NÃO SUPORTADO',
    'profile.status_permission': 'Permissão',
    'profile.push_resync': 'RE-SINCRONIZAR NOTIFICAÇÕES',
    'push.title': 'Avisos Importantes!',
    'push.description': 'Deseja receber avisos de novas aulas, materiais e comunicados importantes diretamente no seu celular?',
    'push.allow': 'Ativar Notificações',
    'push.deny': 'Agora não',
    'push.success': 'Notificações ativadas com sucesso!',
    'push.blocked': 'Notificações bloqueadas no navegador. Redefina as permissões nas configurações do site.',
    'push.error': 'Não foi possível ativar. Verifique se você está em uma aba segura (HTTPS).',
    'notifications.title': 'Notificações',
    'notifications.clear_all': 'LIMPAR TUDO',
    'notifications.close': 'FECHAR PAINEL',
    'notifications.mark_as_read': 'marcar como lida',
    'notifications.empty': 'Você está em dia!',
    'notifications.empty_desc': 'Nenhuma notificação por aqui.',
    'pwa.install_title': 'Instale nosso aplicativo 📲',
    'pwa.install_desc': 'Tenha acesso rápido, sem precisar abrir o navegador',
    'pwa.ios_label': 'Instale manualmente no seu iPhone',
    'pwa.android_label': 'Instale com um clique',
    'pwa.desktop_label': 'Instale direto no seu computador',
    'pwa.ios_step1': 'Toque no ícone de compartilhar',
    'pwa.ios_step2': 'Selecione "Adicionar à Tela de Início"',
    'pwa.android_step1': 'Clique no botão Instalar abaixo',
    'pwa.desktop_step1': 'Use o ícone na barra de endereços',
    'pwa.got_it': 'ENTENDI',
    'pwa.install_button': 'INSTALAR AGORA',
    'pwa.already_installed': 'JÁ INSTALEI',
    'pwa.install_app': '📲 Instalar App',
    'pwa.auto_slide_interval': '3',
    'pwa.steps.ios': '["Toque no ícone de compartilhar", "Selecione \\"Adicionar à Tela de Início\\""]',
    'pwa.steps.android': '["Clique no botão Instalar abaixo"]',
    'pwa.steps.desktop': '["Use o ícone na barra de endereços"]'
  },
  en: {
    'auth.welcome_back': 'Welcome back!',
    'auth.subtitle': 'Access your exclusive area',
    'auth.login': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.restricted_access': 'Restricted Access Notice',
    'auth.restricted_access_msg': 'Restricted access to registered users.',
    'auth.logout_success': 'See you soon!',
    'auth.support_box': 'Need Support?',
    'auth.support_description': 'Our team is ready to help you with any questions or technical issues.',
    'auth.whatsapp_label': 'WhatsApp',
    'auth.email_label': 'Email',
    'auth.user_not_found': 'User not found',
    'auth.disclaimer': 'By entering, you agree to our Terms of Use and Privacy Policy. Premium Motherhood! © 2026',
    'nav.home': 'Home',
    'nav.community': 'Community',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'global.save': 'Save',
    'global.cancel': 'Cancel',
    'global.delete': 'Delete',
    'global.back': 'Back',
    'global.logout': 'Logout',
    'dashboard.courses_paid': 'My Courses',
    'dashboard.courses_free': 'Main Products',
    'dashboard.courses_bonus': 'My Bonuses',
    'course.progress': 'Your Progress',
    'course.your_progress': 'Your Progress',
    'course.lessons': 'Lessons',
    'course.content': 'Content',
    'course.no_media': 'Lesson without media content',
    'course.lesson_completed': 'Lesson completed!',
    'course.prev_lesson': 'Previous Lesson',
    'course.next_lesson': 'Next Lesson',
    'course.materials': 'Materials',
    'course.lesson_unmarked': 'Lesson marked as not completed',
    'course.lesson_completed_btn': 'LESSON COMPLETED',
    'course.complete_lesson_btn': 'FINISH LESSON',
    'course.end_label': 'End',
    'course.support_description': 'Our team is ready to help you.',
    'course.premium_content': 'PREMIUM CONTENT',
    'course.unlock_button': 'UNLOCK ACCESS NOW',
    'course.secure_payment': '100% Secure Payment • Immediate Access',
    'course.schedule_title': 'Course Schedule',
    'course.completed': 'COMPLETED',
    'course.continue': 'CONTINUE',
    'course.start': 'START',
    'community.title': 'Community',
    'community.subtitle': 'Share your journey with other moms',
    'community.input_placeholder': 'What do you want to share?',
    'community.post': 'Post',
    'community.like': 'Like',
    'community.reply': 'Reply',
    'community.delete_post': 'Delete Post',
    'community.add_photo': 'Add Photo',
    'community.post_sent': 'Post sent!',
    'community.post_updated': 'Post updated!',
    'community.edit_post': 'Edit Post',
    'community.delete_post_confirm': 'Delete Post?',
    'community.delete_comment_confirm': 'Delete Comment?',
    'community.comment_placeholder': 'Write a comment...',
    'community.delete_post_desc': 'This action cannot be undone. The post and its image will be permanently removed.',
    'community.delete_comment_desc': 'The comment will be permanently removed.',
    'community.delete_success': 'Post deleted successfully!',
    'community.delete_error': 'Error deleting post',
    'community.comment_delete_success': 'Comment deleted successfully!',
    'community.comment_delete_error': 'Error deleting comment',
    'community.date_format': 'MMM d, h:mm a',
    'community.locale': 'enUS',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your information',
    'profile.save_changes': 'Save Changes',
    'profile.change_password': 'Change Password',
    'profile.update_success': 'Profile updated successfully!',
    'profile.avatar_success': 'Profile picture updated!',
    'profile.password_mismatch': 'Passwords do not match',
    'profile.password_success': 'Password updated successfully!',
    'profile.change_photo': 'Change picture',
    'profile.info_title': 'User Information',
    'profile.access': 'Access',
    'profile.email_restricted': 'Email cannot be changed.',
    'profile.name_label': 'Name',
    'profile.name_placeholder': 'Your name',
    'profile.phone_label': 'Phone (WhatsApp)',
    'profile.phone_country_code': 'Country code',
    'profile.phone_number_label': 'Phone with area code',
    'profile.security_title': 'Security',
    'profile.new_password_label': 'New Password',
    'profile.confirm_password_label': 'Confirm New Password',
    'profile.update_password': 'UPDATE PASSWORD',
    'profile.push_title': 'Push Notifications',
    'profile.push_description': 'Receive important notices, new classes, and community updates directly in your browser.',
    'profile.status_support': 'Support',
    'profile.status_available': 'AVAILABLE',
    'profile.status_not_supported': 'NOT SUPPORTED',
    'profile.status_permission': 'Permission',
    'profile.push_resync': 'RE-SYNC NOTIFICATIONS',
    'push.title': 'Important Notifications!',
    'push.description': 'Would you like to receive notifications of new classes, materials, and important announcements directly on your phone?',
    'push.allow': 'Enable Notifications',
    'push.deny': 'Not now',
    'push.success': 'Notifications enabled successfully!',
    'push.blocked': 'Notifications blocked in browser. Reset permissions in site settings.',
    'push.error': 'Could not enable. Check if you are on a secure (HTTPS) tab.',
    'notifications.title': 'Notifications',
    'notifications.clear_all': 'CLEAR ALL',
    'notifications.close': 'CLOSE PANEL',
    'notifications.mark_as_read': 'mark as read',
    'notifications.empty': 'You are up to date!',
    'notifications.empty_desc': 'No notifications here.',
    'pwa.install_title': 'Install our app 📲',
    'pwa.install_desc': 'Get fast access, without opening the browser',
    'pwa.ios_label': 'Install manually on your iPhone',
    'pwa.android_label': 'Install with one click',
    'pwa.desktop_label': 'Install directly on your computer',
    'pwa.ios_step1': 'Tap the share icon',
    'pwa.ios_step2': 'Select "Add to Home Screen"',
    'pwa.android_step1': 'Click the Install button below',
    'pwa.desktop_step1': 'Use the icon in the address bar',
    'pwa.got_it': 'GOT IT',
    'pwa.install_button': 'INSTALL NOW',
    'pwa.already_installed': 'ALREADY INSTALLED',
    'pwa.install_app': '📲 Install App'
  },
  es: {
    'auth.welcome_back': '¡Bienvenido de nuevo!',
    'auth.subtitle': 'Accede a tu área exclusiva',
    'auth.login': 'Entrar',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.restricted_access': 'Aviso de Acceso Restringido',
    'auth.restricted_access_msg': 'Acceso restringido a alumnas registradas.',
    'auth.logout_success': '¡Hasta pronto!',
    'auth.support_box': '¿Necesitas Ayuda?',
    'auth.support_description': 'Nuestro equipo está listo para ayudarte con cualquier duda o problema técnico.',
    'auth.whatsapp_label': 'WhatsApp',
    'auth.email_label': 'Correo',
    'auth.user_not_found': 'Usuario no encontrado',
    'auth.disclaimer': 'Al entrar, aceptas nuestros Términos de Uso y Política de Privacidad. ¡Maternidad Premium! © 2026',
    'nav.home': 'Inicio',
    'nav.community': 'Comunidad',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'global.save': 'Guardar',
    'global.cancel': 'Cancelar',
    'global.delete': 'Eliminar',
    'global.back': 'Volver',
    'global.logout': 'Salir',
    'dashboard.courses_paid': 'Mis Cursos',
    'dashboard.courses_free': 'Productos Principales',
    'dashboard.courses_bonus': 'Mis Bonos',
    'course.progress': 'Tu Progreso',
    'course.your_progress': 'Tu Progresso',
    'course.lessons': 'Lecciones',
    'course.content': 'Contenido',
    'course.no_media': 'Lección sin contenido multimedia',
    'course.lesson_completed': '¡Lección completada!',
    'course.prev_lesson': 'Lección Anterior',
    'course.next_lesson': 'Próxima Lección',
    'course.materials': 'Materiales',
    'course.lesson_unmarked': 'Lección marcada como no finalizada',
    'course.lesson_completed_btn': 'LECCIÓN COMPLETADA',
    'course.complete_lesson_btn': 'FINALIZAR LECCIÓN',
    'course.end_label': 'Fin',
    'course.support_description': 'Nuestro equipo está listo para ayudarte.',
    'course.premium_content': 'CONTENIDO PREMIUM',
    'course.unlock_button': 'LIBERAR ACCESO AHORA',
    'course.secure_payment': 'Pago 100% Seguro • Acceso Inmediato',
    'course.schedule_title': 'Cronograma del Curso',
    'course.completed': 'COMPLETADO',
    'course.continue': 'CONTINUAR',
    'course.start': 'COMENZAR',
    'community.title': 'Comunidad',
    'community.subtitle': 'Comparte tu jornada con otras madres',
    'community.input_placeholder': '¿Qué quieres compartir?',
    'community.post': 'Publicar',
    'community.like': 'Me gusta',
    'community.reply': 'Responder',
    'community.delete_post': 'Eliminar Publicación',
    'community.add_photo': 'Agregar foto',
    'community.post_sent': '¡Post enviado!',
    'community.post_updated': '¡Post actualizado!',
    'community.edit_post': 'Editar Publicación',
    'community.delete_post_confirm': '¿Eliminar Publicación?',
    'community.delete_comment_confirm': '¿Eliminar Comentario?',
    'community.comment_placeholder': 'Escribe un comentario...',
    'community.delete_post_desc': 'Esta acción no se puede deshacer. La publicación y su imagen se eliminarán permanentemente.',
    'community.delete_comment_desc': 'El comentario se eliminará permanentemente.',
    'community.delete_success': '¡Publicación eliminada con éxito!',
    'community.delete_error': 'Error al eliminar publicación',
    'community.comment_delete_success': '¡Comentario eliminado con éxito!',
    'community.comment_delete_error': 'Error al eliminar comentario',
    'community.date_format': 'd MMM, HH:mm',
    'community.locale': 'es',
    'profile.title': 'Mi Perfil',
    'profile.subtitle': 'Gestiona tu información',
    'profile.save_changes': 'Guardar Cambios',
    'profile.change_password': 'Cambiar Contraseña',
    'profile.update_success': '¡Perfil actualizado con éxito!',
    'profile.avatar_success': '¡Foto de perfil actualizada!',
    'profile.password_mismatch': 'Las contraseñas no coinciden',
    'profile.password_success': '¡Contraseña actualizada con éxito!',
    'profile.change_photo': 'Cambiar foto',
    'profile.info_title': 'Información del Usuario',
    'profile.access': 'Acceso',
    'profile.email_restricted': 'El correo electrónico no se puede cambiar.',
    'profile.name_label': 'Nombre',
    'profile.name_placeholder': 'Tu nombre',
    'profile.phone_label': 'Teléfono (WhatsApp)',
    'profile.phone_country_code': 'Código de país',
    'profile.phone_number_label': 'Teléfono con código de área',
    'profile.security_title': 'Seguridad',
    'profile.new_password_label': 'Nueva Contraseña',
    'profile.confirm_password_label': 'Confirmar Nueva Contraseña',
    'profile.update_password': 'ACTUALIZAR CONTRASEÑA',
    'profile.push_title': 'Notificaciones Push',
    'profile.push_description': 'Reciba avisos importantes, nuevas clases y actualizaciones de la comunidad directamente en su navegador.',
    'profile.status_support': 'Soporte',
    'profile.status_available': 'DISPONIBLE',
    'profile.status_not_supported': 'NO SOPORTADO',
    'profile.status_permission': 'Permiso',
    'profile.push_resync': 'RE-SINCRO NOTIFICACIONES',
    'push.title': '¡Avisos Importantes!',
    'push.description': '¿Deseas recibir avisos de nuevas clases, materiales y comunicados importantes directamente en tu celular?',
    'push.allow': 'Activar Notificaciones',
    'push.deny': 'Ahora no',
    'push.success': '¡Notificaciones activadas con éxito!',
    'push.blocked': 'Notificaciones bloqueadas en el navegador. Restablezca los permisos en la configuración del sitio.',
    'push.error': 'No se pudo activar. Verifique si está en una pestaña segura (HTTPS).',
    'notifications.title': 'Notificaciones',
    'notifications.clear_all': 'LIMPIAR TODO',
    'notifications.close': 'CERRAR PANEL',
    'notifications.mark_as_read': 'marcar como leída',
    'notifications.empty': '¡Estás al día!',
    'notifications.empty_desc': 'No hay notificaciones por aquí.',
    'pwa.install_title': 'Instala nuestra app 📲',
    'pwa.install_desc': 'Ten acceso rápido, sin abrir el navegador',
    'pwa.ios_label': 'Instala manualmente en tu iPhone',
    'pwa.android_label': 'Instala con un clic',
    'pwa.desktop_label': 'Instala directo en tu ordenador',
    'pwa.ios_step1': 'Toca el icono de compartir',
    'pwa.ios_step2': 'Selecciona "Añadir a la pantalla de inicio"',
    'pwa.android_step1': 'Haz clic en el botón Instalar abajo',
    'pwa.desktop_step1': 'Usa el icono en la barra de direcciones',
    'pwa.got_it': 'ENTENDIDO',
    'pwa.install_button': 'INSTALAR AHORA',
    'pwa.already_installed': 'YA INSTALÉ',
    'pwa.install_app': '📲 Instalar App'
  }
};
